services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./homepage/config:/app/config/custom
      - ./homepage/settings.yaml:/app/settings.yaml
      - ./homepage/services.yaml:/app/services.yaml
      - ./homepage/bookmarks.yaml:/app/bookmarks.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: "./homepage/.env"

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      #- ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
