title: Pierremalle Homepage
description: Pierremalle homepage, dedicated to own multiples services and projects in my future house.
startUrl: https://homepage.pierremalle.dev
theme: dark
color: emerald
